### ISSUE TITLE
No PNG Error

### ISSUE THREAD

**Issue by raguay** [zeitlings/alfred-calendar#1]
Hi,

Just ran the workflow for the first time and I'm getting this error:

```
[09:31:09.348] ERROR: Calendar++[Script Filter] Code 1: {
  "items" : [
    {
      "title" : "The file “February3.png” doesn’t exist.",
      "arg" : "The file “February3.png” doesn’t exist.",
      "subtitle" : "",
      "valid" : true,
      "icon" : {
        "path" : "icons\/triangle-exclamation.png"
      }
    }
  ]
}
```

I'm on a macOS MacBook Pro M1 chip set system.

**Comment by zeitlings** [comment]
Curious. Are you still working with macOS 12.X? It looks like the rasterization of the icon is failing on your end. The update might fix the problem. If not, it will set the icon to the workflow default rather than throwing the error.

https://github.com/zeitlings/alfred-calendar/releases/tag/v0.1.1

**Comment by raguay** [comment]
No, I have Ventura 13.1 (22C65). But, this version does seem to work. Thanks.

**Comment by spencertiedge** [comment]
Hi @zeitlings  —  I am running v0.1.1 and Ventura 13.1 and getting this same error. Also on a M1 chip.

**Comment by zeitlings** [comment]
Hey @spencertiedge, could you copy-paste the error from the Alfred debugger (cmd+d)? The error message that raguay posted above should no longer exist in the updated version. You can try `calreset` and perhaps manually delete the executable before re-importing the workflow to make sure it is replaced.

**Comment by spencertiedge** [comment]
Sure thing — see below.

v0.1.1 was the first version of the workflow I downloaded / imported; I did try deleting and re-importing with no luck, however.

```
[16:33:01.516] ERROR: Calendar++[Script Filter] Code 1: 2023-02-07 16:33:01.441 calpp[26742:1173732] The file “February7.png” doesn’t exist. - calpp/IconRenderer.swift:121
[16:33:01.517] Calendar++[Script Filter] {
  "items" : [
    {
      "title" : "Unhandled case encountered",
      "arg" : "Unhandled case encountered",
      "subtitle" : "Theme Identifier: theme.urlimport.C41F537E-D6EE-42D4-AFB1-41D017356995",
      "valid" : true,
      "icon" : {
        "path" : "icons\/triangle-exclamation.png"
      }
    }
  ]
}
```

**Comment by zeitlings** [comment]
Aha! We've discovered a new theme identifier prefix case. This should work now:
https://github.com/zeitlings/alfred-calendar/releases/tag/v0.1.2

**Comment by spencertiedge** [comment]
That was quick :) 

Seems to working now, thanks @zeitlings — this is an awesome workflow!
