### ISSUE TITLE
Something went wrong trying to request access to Calendar

### ISSUE THREAD

**Issue by kellyarwine** [zeitlings/alfred-calendar#2]
This workflow looks super promising. This is the error I'm getting:

```[11:57:15.056] Calendar++[Script Filter] Queuing argument '(null)'
[11:57:15.392] Calendar++[Script Filter] Script with argv '(null)' finished
[11:57:15.397] ERROR: Calendar++[Script Filter] Code 1: 2024-01-06 11:57:15.201 calpp[33695:3438620] The file “January6.png” doesn’t exist. - calpp/IconRenderer.swift:121
[11:57:15.399] Calendar++[Script Filter] {
  "items" : [
    {
      "subtitle" : "",
      "arg" : "Something went wrong trying to request accesss to Calendar but no error was provided",
      "valid" : true,
      "title" : "Something went wrong trying to request accesss to Calendar but no error was provided",
      "icon" : {
        "path" : "icons\/triangle-exclamation.png"
      }
    }
  ]
}
```

Also, I'm assuming it needs an API token, but I'm not seeing where to add one.

**Comment by kellyarwine** [comment]
Ah, I found [this](https://github.com/zeitlings/alfred-calendar/issues/1) but I still have an error. If I type `cal[space]` I get the following:

```[12:07:24.806] Calendar++[Script Filter] Queuing argument ' '
[12:07:25.130] Calendar++[Script Filter] Script with argv ' ' finished
[12:07:25.131] ERROR: Calendar++[Script Filter] Code 1: 2024-01-06 12:07:24.938 calpp[33921:3447861] The file “January6.png” doesn’t exist. - calpp/IconRenderer.swift:121
[12:07:25.137] Calendar++[Script Filter] {
  "items" : [
    {
      "subtitle" : "",
      "valid" : true,
      "arg" : "Something went wrong trying to request accesss to Calendar but no error was provided",
      "icon" : {
        "path" : "icons\/triangle-exclamation.png"
      },
      "title" : "Something went wrong trying to request accesss to Calendar but no error was provided"
    }
  ]
}```

**Comment by zeitlings** [comment]
Hey @kellyarwine, this looks like a permission issue. Make sure that `Alfred 5` and possibly `Calendarpp` have Full Access to your Calendar, otherwise trying to access the Calendar will always fail. 

You can check the permissions here:  System Settings > Privacy & Security > Calendars
Or run this command in the terminal to directly jump to the relevant pane: 
`open x-apple.systempreferences:com.apple.preference.security\?Privacy_Calendars`

**Comment by kellyarwine** [comment]
Thank you @zeitlings! I opened that settings page and do not see neither Alfred 5 nor the Calendarapp in the list. I do see other apps I've installed though. What am I doing wrong? Is the thought that I would double click on the workflow and it would show up in Alfred and also show up on the Privacy pane? Are there any steps I'm missing?

**Comment by kellyarwine** [comment]
I confirmed I'm using Alfred 5. I'm also using Sonoma if that helps at all.

**Comment by zeitlings** [comment]
@kellyarwine perhaps it's best to start here: [Granting Alfred Permissions on Your Mac](https://www.alfredapp.com/help/getting-started/permissions/). 
I hope that helps!

**Comment by goldenages1989** [comment]
After trying the steps mentioned above, I still can't resolve the issue.

**Comment by kellyarwine** [comment]
I got a new Mac and circled back to this because I really wanted to get it working. On my new Mac, it prompted me for permissions 3 times and instantly started working. I could never get it to work on my old Mac (from 2020). 🤷

**Comment by toobluescientist** [comment]
I have the same issue. I've checked the permissions and all but nothing works.

![SCR-20240527-jqtc](https://github.com/zeitlings/alfred-calendar/assets/66875787/50c417d7-33d9-491b-9dab-75f8c5a6e63a)

Do you have any idea @zeitlings ?

**Comment by zeitlings** [comment]
Hey @toobluescientist, if Alfred has full access already I would expect it to work, but perhaps you can try dragging the `calpp` executable directly into the list of apps that have access to the calendar.

In Alfred, type `> open x-apple.systempreferences:com.apple.preference.security\?Privacy_Calendars` to open the relevant panel and drag in the executable that is located in the workflow files (open any object from the workflow canvas and click the little folder icon on the bottom left to find it). 

<img width="862" alt="SCR-20240527-hxxl" src="https://github.com/zeitlings/alfred-calendar/assets/25689591/96a2459e-5026-4878-8e46-a35df01c81b8">

<img width="486" alt="Screenshot 2024-05-27 at 08 20 22" src="https://github.com/zeitlings/alfred-calendar/assets/25689591/4a7d4f80-61c3-45be-98ee-b2e3a8c994f6">
