### ISSUE TITLE
[Solved] Changing configuration requires clearing the cache

### ISSUE THREAD

**Issue by andylundqvist** [zeitlings/alfred-calendar#4]
I am using Calendar++ 2.1.0 with Alfred 5.5.

If I go to the "Configure Workflow..." window and make changes to for example the Block Calendar icon, Emphasis Style, or anything, then click Save, the changes I made do not take effect.

I even tried restarting Alfred completely, that also didn't help.

Right clicking Calendar++ in Alfred's workflow list and choosing Reload does not help either.

(I have granted access and have the required font, but I doubt this is relevant here.)

**Comment by zeitlings** [comment]
Hey @andylundqvist 
After making some configuration changes, try clearing the cache. Type `cc ? ` > Clear Cache.

**Comment by andylundqvist** [comment]
Thank you, that worked! Feature request: Clear cache on Save. Maybe that is out of your reach though, and on the Alfred level. If so, I request this being mentioned in the description (at least I couldn't find it there).

Thanks for a great workflow!

**Comment by zeitlings** [comment]
> Feature request: Clear cache on Save. Maybe that is out of your reach though, and on the Alfred level.

Yeah, that's a limitation that comes with Alfred, unfortunately. 

> I request this being mentioned in the description (at least I couldn't find it there).

I agree, thanks for pointing it out! That piece of information must have fallen by the wayside when I updated the documentation.
