### ISSUE TITLE
[No macOS 12 support] Error: Code 134: dyld[5636]: Library not loaded: '/usr/lib/swift/libswift_StringProcessing.dylib'

### ISSUE THREAD

**Issue by YunchengHua** [zeitlings/alfred-calendar#5]
Unable to use the workflow: I will face this error on the debug output:

```
[16:26:22.480] ERROR: Calendar++[Script Filter] Code 134: dyld[5634]: Library not loaded: '/usr/lib/swift/libswift_StringProcessing.dylib'
  Referenced from: '/Users/yuncheng/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.336F73A4-25EC-4329-90DB-9D68D3C0E149/src/calpp'
  Reason: tried: '/usr/lib/swift/libswift_StringProcessing.dylib' (no such file), '/usr/lib/libswift_StringProcessing.dylib' (no such file)
```

![Screenshot 2024-09-09 at 4 36 58 PM](https://github.com/user-attachments/assets/68f2bd4b-688a-4106-90c1-8baaaab2feae)

I try reinstall the xcode command line tool, seems not working. 

My system: 
Monterey 12.7.6

Xcode-select: 
xcode-select version 2395.

swift:  
Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-darwin21.6.0

**Comment by zeitlings** [comment]
Hey @YunchengHua 
Another user was able to resolve a similar issue by manually installing Xcode from the App Store.
If that doesn't work, it's possible that Apple dropped support for your Monterey, seeing that your Swift version is outdated (on Sonoma I'm seeing  Swift version 5.10).

**Comment by YunchengHua** [comment]
Thanks for replying.

I try to install Xcode it requires macOS 14.0 and later. 

And then I try to install swift from brew and use swift 5.10, seems still not able to work. I feel maybe the `calpp` didn't use the one installed by brew even though I already export in my path.

![Screenshot 2024-09-09 at 7 06 42 PM](https://github.com/user-attachments/assets/5d688a38-4658-4f81-a828-962cbed458f9)

**Comment by zeitlings** [comment]
Hey, I just checked by pushing the deployment target to 12.0, and, alas:
<img width="245" alt="image" src="https://github.com/user-attachments/assets/1102ec62-f148-4e5a-ab8e-a3f557ed4dba">

I'm afraid there's nothing to be done if you can't update your OS above Monterey 12.7.6.

**Comment by YunchengHua** [comment]
Got it. thanks so much.
