### ISSUE TITLE
Strange font issue with agenda

### ISSUE THREAD

**Issue by noirchen** [zeitlings/alfred-calendar#6]
I find a strange font issue in the agenda. My calendar has subscribed to the US Holidays (https://calendars.icloud.com/holidays/us_en-us.ics), and some holidays are shown with strange characters. I tried switching the font of Alfred but it does not work.

<img width="575" alt="Screenshot 2024-10-10 at 4 30 39 PM" src="https://github.com/user-attachments/assets/80b05067-3321-464b-a7e5-668375e3c0de">

**Comment by zeitlings** [comment]
Hey @noirchen 
Make sure you follow Step 1 of the Setup. Those question marks are most likely SF Symbols that cannot be rendered, because the font is missing. 

> 1. Install the [SF Pro font](https://developer.apple.com/fonts/) from Apple to see the icons

**Comment by noirchen** [comment]
Thanks a lot. This fixes it.
