### ISSUE TITLE
REQUEST: Filter available calendars

### ISSUE THREAD

**Issue by imyelmo** [zeitlings/alfred-calendar#8]
My calendar has a lot of calendar but most of the time, I'm only use a couple of them. It would be very helpful to specify the calendars to be shown by the workflow. Thanks.

**Comment by zeitlings** [comment]
Hey @imyelmo 
This is what the "Ignored Calendars" configuration option is for:

<img width="534" alt="image" src="https://github.com/user-attachments/assets/f6e19d59-f518-47a9-81a2-5d2a7878bd3d">
